routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('feeds.index');
});

Route::resources([
    'feeds' => 'FeedController',
]);

app/Feed.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feed extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'url'
    ];

    /**
     * Remove trailed slash in url.
     *
     * @param string $url
     * @return string
     */
    public static function removeTrailedSlash($url)
    {
        return rtrim($url, '\/');
    }

    /**
     * Load feeds from provided url.
     *
     * @param string $url
     * @return array
     */
    public static function loadFeedsFromUrl($url)
    {
        try {
            $xmlData = file_get_contents($url);
            $articles = [];

            if ($xmlData !== false) {
                $xmlData = json_decode(json_encode(simplexml_load_string($xmlData)));

                if (is_object($xmlData)) {
                    if (isset($xmlData->channel) && isset($xmlData->channel->item)) {
                        foreach ($xmlData->channel->item as $item) {
                            $articles[] = [
                                'title' => !empty($item->title) ? $item->title : '',
                                'pubDate' => !empty($item->pubDate) ? $item->pubDate : '',
                                'link' => !empty($item->link) ? $item->link : ''
                            ];
                        }
                    }

                    if (isset($xmlData->entry)) {
                        foreach ($xmlData->entry as $entry) {
                            $articles[] = [
                                'title' => !empty($entry->title) ? $entry->title : '',
                                'pubDate' => !empty($entry->published) ? $entry->published : '',
                                'link' => !empty($entry->link) && !empty($entry->link) && !empty($entry->link->{'@attributes'}) && !empty($entry->link->{'@attributes'}->href) ? $entry->link->{'@attributes'}->href : ''
                            ];
                        }
                    }
                }
            }

            return $articles;
        } catch (\Exception $e) {
            return [];
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use App\Feed;
use Illuminate\Http\Request;

class FeedController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = \DB::table('feeds');

        if ($sign = $request->input('query')) {
            $query = $query->where('url', 'like', '%' . $sign . '%')
                ->orWhere('title', 'like', '%' . $sign . '%');
        }

        $feeds = $query->get();

        return view('feed.index', [
            'title' => 'Feeds',
            'feeds' => $feeds
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $feed = new Feed;

        return view('feed.create', [
            'title' => 'New Feed',
            'feed' => $feed
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:191',
            'url' => 'required|url|max:191|unique:feeds',
        ]);

        $feed = new Feed;
        $feed->title = $request->title;
        $feed->url = Feed::removeTrailedSlash($request->url);
        $saved = $feed->save();

        if (!$saved) {
            \Session::flash('error', 'Feed unsuccessfully added.');
            return back()->withInput();
        }

        \Session::flash('success', 'Feed successfully added.');
        return redirect()->route('feeds.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Feed $feed
     * @return \Illuminate\Http\Response
     */
    public function show(Feed $feed)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Feed $feed
     * @return \Illuminate\Http\Response
     */
    public function edit(Feed $feed)
    {
        return view('feed.edit', [
            'title' => 'Feed ID: ' . $feed->id,
            'feed' => $feed,
            'articles' => Feed::loadFeedsFromUrl($feed->url)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Feed $feed
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Feed $feed)
    {
        $request->validate([
            'title' => 'required|max:191',
            'url' => 'required|url|max:191' . ($feed->url == Feed::removeTrailedSlash($request->url) ? '' : '|unique:feeds'),
        ]);

        $feed->title = $request->title;
        $feed->url = Feed::removeTrailedSlash($request->url);
        $saved = $feed->save();

        if (!$saved) {
            \Session::flash('error', 'Feed unsuccessfully updated.');
            return back()->withInput();
        }

        \Session::flash('success', 'Feed successfully updated.');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Feed $feed
     * @return \Illuminate\Http\Response
     */
    public function destroy(Feed $feed)
    {
        $deleted = $feed->delete();

        if (is_null($deleted) || $deleted === true) {
            \Session::flash('success', 'Feed successfully deleted.');
            return redirect()->route('feeds.index');
        }

        \Session::flash('error', 'Feed unsuccessfully deleted.');
        return back();
    }
}

resources/views/feed/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="col-sm-12">
        {!! Form::model($feed, ['route' => 'feeds.store']) !!}
        <div class="form-group">
            {!! Form::label('title', 'Title') !!}
            {!! Form::text('title', old('title', $feed->title), ['class' => 'form-control ' . ($errors->has('title') ? 'is-invalid' : '')]) !!}
            @error('title')
            <div class="text-danger">
                <small>{{ $message }}</small>
            </div>
            @enderror
        </div>

        <div class="form-group">
            {!! Form::label('url', 'Url') !!}
            {!! Form::text('url', old('url', $feed->url), ['class' => 'form-control ' . ($errors->has('url') ? 'is-invalid' : '')]) !!}
            @error('url')
            <div class="text-danger">
                <small>{{ $message }}</small>
            </div>
            @enderror
        </div>

        <div class="text-center">
            <button class="btn btn-success" type="submit">
                <i class="fa fa-plus"></i>
                Create Feed
            </button>
            <a class="btn btn-warning" href="{{ route('feeds.index') }}">
                <i class="fa fa-chevron-left"></i>
                Back
            </a>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/feed/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="col-sm-12">
        {!! Form::model($feed, ['route' => ['feeds.update', $feed->id], 'method' => 'put']) !!}
        <div class="form-group">
            {!! Form::label('title', 'Title') !!}
            {!! Form::text('title', old('title', $feed->title), ['class' => 'form-control ' . ($errors->has('title') ? 'is-invalid' : '')]) !!}
            @error('title')
            <div class="text-danger">
                <small>{{ $message }}</small>
            </div>
            @enderror
        </div>

        <div class="form-group">
            {!! Form::label('url', 'Url') !!}
            {!! Form::text('url', old('url', $feed->url), ['class' => 'form-control ' . ($errors->has('url') ? 'is-invalid' : '')]) !!}
            @error('url')
            <div class="text-danger">
                <small>{{ $message }}</small>
            </div>
            @enderror
        </div>

        <div class="text-center">
            <button class="btn btn-success" type="submit">
                <i class="fa fa-pencil"></i>
                Save Feed
            </button>
            <a class="btn btn-warning" href="{{ route('feeds.index') }}">
                <i class="fa fa-chevron-left"></i>
                Back
            </a>
        </div>

        <h5>Articles</h5>
        <ul>
            @if (! empty($articles))
                @foreach ($articles as $article)
                    <li>
                        <a target="blank" href="{{ $article['link'] }}">{{ $article['title'] }}</a>
                    </li>
                @endforeach
            @else
                <li>No articles found</li>
            @endif
        </ul>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/feed/index.blade.php
@extends('layouts.master')

@section('header_buttons')
    @parent
    <div class="col-sm-12">
        <div class="margin-top-15px text-right">
            <a href="{{ route('feeds.create') }}" class="btn btn-outline-info">
                <i class="fa fa-plus"></i>
                New Feed
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div class="col-sm-12">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Url</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @if (count($feeds))
                @foreach ($feeds as $index => $feed)
                    <tr>
                        <th scope="row">{{ $index + 1 }}</th>
                        <td><a href="{{ route('feeds.edit', ['feed' => $feed->id]) }}">{{ $feed->title }}</a></td>
                        <td><a target="blank" href="{{ $feed->url }}">{{ $feed->url }}</a></td>
                        <td>
                            {!! Form::model($feed, ['route' => ['feeds.update', $feed->id], 'method' => 'delete']) !!}
                            <button class="btn btn-outline-danger" onclick="return confirm('Are you sure about deleting this feed?')" type="submit">
                                <i class="fa fa-trash"></i>
                                Delete
                            </button>
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <th scope="row" colspan="4" class="text-center">No feeds found</th>
                </tr>
            @endif
            </tbody>
        </table>
    </div>
@endsection

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>

    <title>Feed Manager</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .margin-15px {
            margin: 15px;
        }

        .margin-top-15px {
            margin-top: 15px;
        }

        .margin-bot-15px {
            margin-bottom: 15px;
        }

        .margin-left-15px {
            margin-left: 15px;
        }

        .margin-right-15px {
            margin-right: 15px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="/">Feed Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <!-- <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li> -->
                    </ul>
                    <form class="form-inline my-2 my-lg-0" action="{{ route('feeds.index') }}">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                               name="query" value="{{ app('request')->input('query') }}">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                            <i class="fa fa-search"></i>
                            Search
                        </button>
                    </form>
                </div>
            </nav>
        </div>
    </div>
    <div class="row">
        @section('header_buttons')
        @show

        <div class="col-sm-12">
            <h3>{{ $title }}</h3>
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if ($message = Session::get('error'))
                <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if ($message = Session::get('warning'))
                <div class="alert alert-warning alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if ($message = Session::get('info'))
                <div class="alert alert-info alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    Please check the form below for errors
                </div>
            @endif
        </div>

        @yield('content')
    </div>
</div>
</body>
<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</html>